In [1]:
import gym
import random
import datetime
import torch
import numpy as np
from collections import deque
import matplotlib.pyplot as plt
%matplotlib inline

from model import *
import utils
from parallelEnv import parallelEnv

# imports for rendering outputs in Jupyter.
from JSAnimation.IPython_display import display_animation
from matplotlib import animation
from IPython.display import display

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [2]:
env = gym.make('BipedalWalker-v2')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
#lets print out some info about the env
print ("Action space: {}\t Observation space: {}".format(env.action_space,env.observation_space))

Action space: Box(4,)	 Observation space: Box(24,)


In [4]:
#lets play a random episode
state = env.reset()
done = False
step_count = 0
while not done:
    action = env.action_space.sample()
    next_state,reward,done,_ = env.step(action)
    
    print ("Step: {}\t state: {}...\t action: {}\t done: {}\n".format(step_count,state[:4],action,done))
    
    state = next_state
    step_count+=1

Step: 0	 state: [ 2.74736132e-03 -1.80533796e-05  1.40437089e-03 -1.59998786e-02]...	 action: [0.09762701 0.43037874 0.20552675 0.08976637]	 done: False

Step: 1	 state: [ 0.00245539 -0.00693409  0.0070726   0.01954935]...	 action: [-0.1526904   0.29178822 -0.12482557  0.78354603]	 done: False

Step: 2	 state: [0.0025491  0.00254573 0.00922413 0.00672575]...	 action: [ 0.92732555 -0.23311697  0.5834501   0.05778984]	 done: False

Step: 3	 state: [-0.02497795 -0.05565681 -0.0322394  -0.0114644 ]...	 action: [ 0.13608912  0.85119325 -0.85792786 -0.8257414 ]	 done: False

Step: 4	 state: [-0.03810742 -0.02684064 -0.01018439 -0.00028265]...	 action: [-0.9595632   0.6652397   0.5563135   0.74002427]	 done: False

Step: 5	 state: [-0.04034078 -0.00448927  0.02452209  0.07418856]...	 action: [ 0.9572367   0.59831715 -0.07704128  0.56105834]	 done: False

Step: 6	 state: [-0.05752924 -0.03441599  0.01659872  0.0676573 ]...	 action: [-0.76345116  0.27984205 -0.71329343  0.88933784]	 done: False

In [5]:
random_seed = 0

#set random seed for env
env.seed(0)

# define policy
actor = Actor(state_size=env.observation_space.shape[0],
               action_size=env.action_space.shape[0],
               seed=random_seed)

critic = Critic()

In [6]:
# check which device is being used. 
# I recommend disabling gpu until you've made sure that the code runs
device = utils.device
print("using device: ",device)

using device:  cpu


In [7]:
envs = parallelEnv('BipedalWalker-v2', n=8, seed=1234)

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.

In [8]:
envs.action_space.sample()

array([-0.7103045 , -0.02388744, -0.28877452,  0.8808639 ], dtype=float32)

In [9]:
class PPO:
    def __init__(self):
        pass
    
    def act(self,state):
        pass
    
    def learn(self,experience):
        pass
    
    def step(self):
        pass

In [23]:
env.action_space.shape

(4,)

In [48]:
a = torch.from_numpy(np.array([1,2,3])/np.array([2,2,2]))

In [49]:
a

tensor([ 0.5000,  1.0000,  1.5000], dtype=torch.float64)

In [50]:
torch.clamp(a,.8,1.2) 

tensor([ 0.8000,  1.0000,  1.2000], dtype=torch.float64)